In [1]:
import warnings
warnings.filterwarnings('ignore')
from sklearn.datasets import load_iris
import pandas as pd
iris = load_iris()
x = pd.DataFrame(iris.data, columns=[iris.feature_names])
y = pd.Series(iris.target)

In [2]:
x.head()

sepal length (cm) sepal width (cm) petal length (cm) petal width (cm)
0               5.1              3.5               1.4              0.2
1               4.9              3.0               1.4              0.2
2               4.7              3.2               1.3              0.2
3               4.6              3.1               1.5              0.2
4               5.0              3.6               1.4              0.2

In [3]:
y.value_counts()

0    50
1    50
2    50
Name: count, dtype: int64

In [7]:
#!pip3 install tensorflow
#Não faça mais nada de instalação, muito menos no ANACONDA!

In [9]:
import tensorflow
import keras
from tensorflow.python.keras.utils import np_utils
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D,Dropout
from tensorflow.keras.layers import Dense, Activation, Flatten
from tensorflow.keras.utils import to_categorical
from tensorflow.keras import backend as K 
from sklearn.model_selection import train_test_split
from tensorflow.keras import callbacks 
y_convertido = np_utils.to_categorical(y) #convertendo a coluna de valores em uma matriz de classes (one hot encoding)

In [10]:
y_convertido

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [11]:
from sklearn.model_selection import train_test_split
x_treino, x_teste, y_treino, y_teste = train_test_split(x, y_convertido, test_size = 0.3)# 30% para teste

In [12]:
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.optimizers import SGD

In [14]:
modelo = Sequential()
#Construimos a rede neural adicionando camadas por meio do comando ".add". O primeiro argumento consiste no nùmero de neurônios
#que aquela camada terá. Também podemos informar o modelo de inicialização das variáveis e a função de ativação nessa camada.
modelo.add(Dense(10, input_dim=4, kernel_initializer='normal', activation='relu')) #input_dim é a quantidade de neurônios de
#entrada, que nesse caso são 4 variáveis preditoras
modelo.add(Dense(3, kernel_initializer='normal', activation='softmax')) #Essa é a saida (3 neurônios pois são 3 classes)
#A função softmax para a saída costuma ser usada em problemas de classificação. Ela dá como resultado probabilidades de pertencer
#a cada uma das classes (softmax / sigmoid / relu)

In [15]:
otimizador = keras.optimizers.SGD()

In [16]:
x_treino.shape

(105, 4)

In [17]:
modelo.compile(loss='categorical_crossentropy', optimizer=otimizador, metrics=['acc']) #"acc" é a metrica de acurácia
modelo.fit(x_treino, y_treino, epochs=1000, batch_size=105, validation_data=(x_teste, y_teste), verbose=1)

Epoch 1/1000


1/1 [==============================] - 1s 687ms/step - loss: 1.0873 - acc: 0.3238 - val_loss: 1.0843 - val_acc: 0.3556
Epoch 2/1000
1/1 [==============================] - 0s 28ms/step - loss: 1.0870 - acc: 0.3238 - val_loss: 1.0840 - val_acc: 0.3556
Epoch 3/1000
1/1 [==============================] - 0s 32ms/step - loss: 1.0867 - acc: 0.3238 - val_loss: 1.0836 - val_acc: 0.3556
Epoch 4/1000
1/1 [==============================] - 0s 32ms/step - loss: 1.0863 - acc: 0.3238 - val_loss: 1.0832 - val_acc: 0.3556
Epoch 5/1000
1/1 [==============================] - 0s 28ms/step - loss: 1.0860 - acc: 0.3238 - val_loss: 1.0829 - val_acc: 0.3556
Epoch 6/1000
1/1 [==============================] - 0s 33ms/step - loss: 1.0856 - acc: 0.3238 - val_loss: 1.0825 - val_acc: 0.3556
Epoch 7/1000
1/1 [==============================] - 0s 31ms/step - loss: 1.0853 - acc: 0.3238 - val_loss: 1.0821 - val_acc: 0.3556
Epoch 8/1000
1/1 [==============================] - 0s 30ms/step - loss: 1.0849 

1/1 [==============================] - 0s 27ms/step - loss: 1.0620 - acc: 0.3238 - val_loss: 1.0577 - val_acc: 0.3556
Epoch 60/1000
1/1 [==============================] - 0s 26ms/step - loss: 1.0614 - acc: 0.3238 - val_loss: 1.0570 - val_acc: 0.3556
Epoch 61/1000
1/1 [==============================] - 0s 29ms/step - loss: 1.0608 - acc: 0.3238 - val_loss: 1.0564 - val_acc: 0.3556
Epoch 62/1000
1/1 [==============================] - 0s 28ms/step - loss: 1.0602 - acc: 0.3238 - val_loss: 1.0558 - val_acc: 0.3556
Epoch 63/1000
1/1 [==============================] - 0s 27ms/step - loss: 1.0596 - acc: 0.3333 - val_loss: 1.0551 - val_acc: 0.3556
Epoch 64/1000
1/1 [==============================] - 0s 27ms/step - loss: 1.0589 - acc: 0.3333 - val_loss: 1.0544 - val_acc: 0.3556
Epoch 65/1000
1/1 [==============================] - 0s 28ms/step - loss: 1.0583 - acc: 0.3333 - val_loss: 1.0538 - val_acc: 0.3556
Epoch 66/1000
1/1 [==============================] - 0s 29ms/step - loss: 1.0576 - acc: 0.

1/1 [==============================] - 0s 31ms/step - loss: 1.0096 - acc: 0.6190 - val_loss: 1.0040 - val_acc: 0.5333
Epoch 122/1000
1/1 [==============================] - 0s 28ms/step - loss: 1.0085 - acc: 0.6190 - val_loss: 1.0029 - val_acc: 0.5333
Epoch 123/1000
1/1 [==============================] - 0s 30ms/step - loss: 1.0074 - acc: 0.6286 - val_loss: 1.0018 - val_acc: 0.5333
Epoch 124/1000
1/1 [==============================] - 0s 29ms/step - loss: 1.0063 - acc: 0.6286 - val_loss: 1.0007 - val_acc: 0.5333
Epoch 125/1000
1/1 [==============================] - 0s 28ms/step - loss: 1.0052 - acc: 0.6381 - val_loss: 0.9995 - val_acc: 0.5333
Epoch 126/1000
1/1 [==============================] - 0s 28ms/step - loss: 1.0040 - acc: 0.6381 - val_loss: 0.9984 - val_acc: 0.5333
Epoch 127/1000
1/1 [==============================] - 0s 29ms/step - loss: 1.0029 - acc: 0.6381 - val_loss: 0.9973 - val_acc: 0.5333
Epoch 128/1000
1/1 [==============================] - 0s 30ms/step - loss: 1.0017 - 

Epoch 183/1000
1/1 [==============================] - 0s 25ms/step - loss: 0.9289 - acc: 0.6857 - val_loss: 0.9255 - val_acc: 0.6222
Epoch 184/1000
1/1 [==============================] - 0s 32ms/step - loss: 0.9275 - acc: 0.6857 - val_loss: 0.9242 - val_acc: 0.6222
Epoch 185/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.9262 - acc: 0.6857 - val_loss: 0.9229 - val_acc: 0.6222
Epoch 186/1000
1/1 [==============================] - 0s 32ms/step - loss: 0.9249 - acc: 0.6857 - val_loss: 0.9215 - val_acc: 0.6222
Epoch 187/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.9235 - acc: 0.6857 - val_loss: 0.9202 - val_acc: 0.6222
Epoch 188/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.9222 - acc: 0.6857 - val_loss: 0.9189 - val_acc: 0.6222
Epoch 189/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.9208 - acc: 0.6857 - val_loss: 0.9176 - val_acc: 0.6222
Epoch 190/1000
1/1 [==============================] - 0s 28ms/step - 

1/1 [==============================] - 0s 27ms/step - loss: 0.8528 - acc: 0.6857 - val_loss: 0.8519 - val_acc: 0.6222
Epoch 245/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.8516 - acc: 0.6857 - val_loss: 0.8509 - val_acc: 0.6222
Epoch 246/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.8505 - acc: 0.6857 - val_loss: 0.8498 - val_acc: 0.6222
Epoch 247/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.8494 - acc: 0.6857 - val_loss: 0.8487 - val_acc: 0.6222
Epoch 248/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.8483 - acc: 0.6857 - val_loss: 0.8477 - val_acc: 0.6222
Epoch 249/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.8472 - acc: 0.6857 - val_loss: 0.8467 - val_acc: 0.6222
Epoch 250/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.8461 - acc: 0.6857 - val_loss: 0.8456 - val_acc: 0.6222
Epoch 251/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.8450 - 

Epoch 306/1000
1/1 [==============================] - 0s 35ms/step - loss: 0.7917 - acc: 0.6857 - val_loss: 0.7942 - val_acc: 0.6222
Epoch 307/1000
1/1 [==============================] - 0s 39ms/step - loss: 0.7909 - acc: 0.6857 - val_loss: 0.7934 - val_acc: 0.6222
Epoch 308/1000
1/1 [==============================] - 0s 34ms/step - loss: 0.7900 - acc: 0.6857 - val_loss: 0.7925 - val_acc: 0.6222
Epoch 309/1000
1/1 [==============================] - 0s 35ms/step - loss: 0.7891 - acc: 0.6857 - val_loss: 0.7917 - val_acc: 0.6222
Epoch 310/1000
1/1 [==============================] - 0s 34ms/step - loss: 0.7883 - acc: 0.6857 - val_loss: 0.7909 - val_acc: 0.6222
Epoch 311/1000
1/1 [==============================] - 0s 34ms/step - loss: 0.7874 - acc: 0.6857 - val_loss: 0.7901 - val_acc: 0.6222
Epoch 312/1000
1/1 [==============================] - 0s 39ms/step - loss: 0.7866 - acc: 0.6857 - val_loss: 0.7894 - val_acc: 0.6222
Epoch 313/1000
1/1 [==============================] - 0s 35ms/step - 

1/1 [==============================] - 0s 31ms/step - loss: 0.7437 - acc: 0.6857 - val_loss: 0.7503 - val_acc: 0.6222
Epoch 368/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.7430 - acc: 0.6857 - val_loss: 0.7496 - val_acc: 0.6222
Epoch 369/1000
1/1 [==============================] - 0s 29ms/step - loss: 0.7423 - acc: 0.6857 - val_loss: 0.7490 - val_acc: 0.6222
Epoch 370/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.7416 - acc: 0.6857 - val_loss: 0.7484 - val_acc: 0.6222
Epoch 371/1000
1/1 [==============================] - 0s 30ms/step - loss: 0.7409 - acc: 0.6857 - val_loss: 0.7478 - val_acc: 0.6222
Epoch 372/1000
1/1 [==============================] - 0s 29ms/step - loss: 0.7402 - acc: 0.6857 - val_loss: 0.7471 - val_acc: 0.6222
Epoch 373/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.7395 - acc: 0.6857 - val_loss: 0.7465 - val_acc: 0.6222
Epoch 374/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.7388 - 

Epoch 429/1000
1/1 [==============================] - 0s 30ms/step - loss: 0.7038 - acc: 0.6857 - val_loss: 0.7149 - val_acc: 0.6222
Epoch 430/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.7032 - acc: 0.6857 - val_loss: 0.7144 - val_acc: 0.6222
Epoch 431/1000
1/1 [==============================] - 0s 31ms/step - loss: 0.7027 - acc: 0.6857 - val_loss: 0.7139 - val_acc: 0.6222
Epoch 432/1000
1/1 [==============================] - 0s 30ms/step - loss: 0.7021 - acc: 0.6857 - val_loss: 0.7134 - val_acc: 0.6222
Epoch 433/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.7015 - acc: 0.6857 - val_loss: 0.7128 - val_acc: 0.6222
Epoch 434/1000
1/1 [==============================] - 0s 31ms/step - loss: 0.7009 - acc: 0.6857 - val_loss: 0.7123 - val_acc: 0.6222
Epoch 435/1000
1/1 [==============================] - 0s 29ms/step - loss: 0.7003 - acc: 0.6857 - val_loss: 0.7118 - val_acc: 0.6222
Epoch 436/1000
1/1 [==============================] - 0s 32ms/step - 

1/1 [==============================] - 0s 31ms/step - loss: 0.6707 - acc: 0.6857 - val_loss: 0.6862 - val_acc: 0.6222
Epoch 491/1000
1/1 [==============================] - 0s 29ms/step - loss: 0.6702 - acc: 0.6857 - val_loss: 0.6857 - val_acc: 0.6222
Epoch 492/1000
1/1 [==============================] - 0s 33ms/step - loss: 0.6697 - acc: 0.6857 - val_loss: 0.6853 - val_acc: 0.6222
Epoch 493/1000
1/1 [==============================] - 0s 31ms/step - loss: 0.6692 - acc: 0.6857 - val_loss: 0.6849 - val_acc: 0.6222
Epoch 494/1000
1/1 [==============================] - 0s 34ms/step - loss: 0.6687 - acc: 0.6857 - val_loss: 0.6845 - val_acc: 0.6222
Epoch 495/1000
1/1 [==============================] - 0s 34ms/step - loss: 0.6682 - acc: 0.6857 - val_loss: 0.6840 - val_acc: 0.6222
Epoch 496/1000
1/1 [==============================] - 0s 40ms/step - loss: 0.6677 - acc: 0.6857 - val_loss: 0.6836 - val_acc: 0.6222
Epoch 497/1000
1/1 [==============================] - 0s 35ms/step - loss: 0.6673 - 

Epoch 552/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.6419 - acc: 0.6857 - val_loss: 0.6614 - val_acc: 0.6222
Epoch 553/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.6414 - acc: 0.6857 - val_loss: 0.6610 - val_acc: 0.6222
Epoch 554/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.6410 - acc: 0.6857 - val_loss: 0.6606 - val_acc: 0.6222
Epoch 555/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.6406 - acc: 0.6857 - val_loss: 0.6603 - val_acc: 0.6222
Epoch 556/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.6401 - acc: 0.6857 - val_loss: 0.6599 - val_acc: 0.6222
Epoch 557/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.6397 - acc: 0.6857 - val_loss: 0.6595 - val_acc: 0.6222
Epoch 558/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.6393 - acc: 0.6857 - val_loss: 0.6591 - val_acc: 0.6222
Epoch 559/1000
1/1 [==============================] - 0s 28ms/step - 

1/1 [==============================] - 0s 30ms/step - loss: 0.6170 - acc: 0.6952 - val_loss: 0.6403 - val_acc: 0.6222
Epoch 614/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.6167 - acc: 0.6952 - val_loss: 0.6400 - val_acc: 0.6222
Epoch 615/1000
1/1 [==============================] - 0s 31ms/step - loss: 0.6163 - acc: 0.6952 - val_loss: 0.6396 - val_acc: 0.6222
Epoch 616/1000
1/1 [==============================] - 0s 30ms/step - loss: 0.6159 - acc: 0.6952 - val_loss: 0.6393 - val_acc: 0.6222
Epoch 617/1000
1/1 [==============================] - 0s 36ms/step - loss: 0.6155 - acc: 0.6952 - val_loss: 0.6390 - val_acc: 0.6222
Epoch 618/1000
1/1 [==============================] - 0s 29ms/step - loss: 0.6152 - acc: 0.6952 - val_loss: 0.6387 - val_acc: 0.6222
Epoch 619/1000
1/1 [==============================] - 0s 29ms/step - loss: 0.6148 - acc: 0.6952 - val_loss: 0.6384 - val_acc: 0.6222
Epoch 620/1000
1/1 [==============================] - 0s 31ms/step - loss: 0.6144 - 

Epoch 675/1000
1/1 [==============================] - 0s 29ms/step - loss: 0.5950 - acc: 0.6952 - val_loss: 0.6214 - val_acc: 0.6222
Epoch 676/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.5947 - acc: 0.6952 - val_loss: 0.6211 - val_acc: 0.6222
Epoch 677/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.5944 - acc: 0.6952 - val_loss: 0.6208 - val_acc: 0.6222
Epoch 678/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.5940 - acc: 0.6952 - val_loss: 0.6206 - val_acc: 0.6222
Epoch 679/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.5937 - acc: 0.6952 - val_loss: 0.6203 - val_acc: 0.6222
Epoch 680/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.5934 - acc: 0.6952 - val_loss: 0.6200 - val_acc: 0.6222
Epoch 681/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.5930 - acc: 0.6952 - val_loss: 0.6197 - val_acc: 0.6222
Epoch 682/1000
1/1 [==============================] - 0s 29ms/step - 

1/1 [==============================] - 0s 26ms/step - loss: 0.5760 - acc: 0.6952 - val_loss: 0.6054 - val_acc: 0.6444
Epoch 737/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.5757 - acc: 0.6952 - val_loss: 0.6051 - val_acc: 0.6444
Epoch 738/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.5754 - acc: 0.6952 - val_loss: 0.6049 - val_acc: 0.6444
Epoch 739/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.5751 - acc: 0.6952 - val_loss: 0.6046 - val_acc: 0.6444
Epoch 740/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.5748 - acc: 0.6952 - val_loss: 0.6044 - val_acc: 0.6444
Epoch 741/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.5745 - acc: 0.6952 - val_loss: 0.6041 - val_acc: 0.6444
Epoch 742/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.5742 - acc: 0.6952 - val_loss: 0.6039 - val_acc: 0.6444
Epoch 743/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.5740 - 

Epoch 798/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.5588 - acc: 0.7143 - val_loss: 0.5904 - val_acc: 0.6444
Epoch 799/1000
1/1 [==============================] - 0s 30ms/step - loss: 0.5585 - acc: 0.7143 - val_loss: 0.5902 - val_acc: 0.6444
Epoch 800/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.5583 - acc: 0.7143 - val_loss: 0.5900 - val_acc: 0.6444
Epoch 801/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.5580 - acc: 0.7143 - val_loss: 0.5898 - val_acc: 0.6444
Epoch 802/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.5578 - acc: 0.7143 - val_loss: 0.5895 - val_acc: 0.6444
Epoch 803/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.5575 - acc: 0.7143 - val_loss: 0.5893 - val_acc: 0.6444
Epoch 804/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.5572 - acc: 0.7143 - val_loss: 0.5891 - val_acc: 0.6444
Epoch 805/1000
1/1 [==============================] - 0s 27ms/step - 

1/1 [==============================] - 0s 27ms/step - loss: 0.5436 - acc: 0.7238 - val_loss: 0.5773 - val_acc: 0.6444
Epoch 860/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.5434 - acc: 0.7238 - val_loss: 0.5771 - val_acc: 0.6444
Epoch 861/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.5431 - acc: 0.7238 - val_loss: 0.5769 - val_acc: 0.6444
Epoch 862/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.5429 - acc: 0.7238 - val_loss: 0.5767 - val_acc: 0.6444
Epoch 863/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.5427 - acc: 0.7238 - val_loss: 0.5765 - val_acc: 0.6444
Epoch 864/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.5424 - acc: 0.7238 - val_loss: 0.5763 - val_acc: 0.6444
Epoch 865/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.5422 - acc: 0.7238 - val_loss: 0.5761 - val_acc: 0.6444
Epoch 866/1000
1/1 [==============================] - 0s 29ms/step - loss: 0.5420 - 

Epoch 921/1000
1/1 [==============================] - 0s 31ms/step - loss: 0.5297 - acc: 0.7238 - val_loss: 0.5651 - val_acc: 0.6444
Epoch 922/1000
1/1 [==============================] - 0s 31ms/step - loss: 0.5295 - acc: 0.7238 - val_loss: 0.5649 - val_acc: 0.6444
Epoch 923/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.5292 - acc: 0.7238 - val_loss: 0.5647 - val_acc: 0.6444
Epoch 924/1000
1/1 [==============================] - 0s 29ms/step - loss: 0.5290 - acc: 0.7238 - val_loss: 0.5646 - val_acc: 0.6444
Epoch 925/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.5288 - acc: 0.7238 - val_loss: 0.5644 - val_acc: 0.6444
Epoch 926/1000
1/1 [==============================] - 0s 29ms/step - loss: 0.5286 - acc: 0.7238 - val_loss: 0.5642 - val_acc: 0.6444
Epoch 927/1000
1/1 [==============================] - 0s 30ms/step - loss: 0.5284 - acc: 0.7238 - val_loss: 0.5640 - val_acc: 0.6444
Epoch 928/1000
1/1 [==============================] - 0s 35ms/step - 

1/1 [==============================] - 0s 32ms/step - loss: 0.5172 - acc: 0.7238 - val_loss: 0.5541 - val_acc: 0.6667
Epoch 983/1000
1/1 [==============================] - 0s 30ms/step - loss: 0.5170 - acc: 0.7238 - val_loss: 0.5539 - val_acc: 0.6667
Epoch 984/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.5168 - acc: 0.7238 - val_loss: 0.5537 - val_acc: 0.6667
Epoch 985/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.5166 - acc: 0.7238 - val_loss: 0.5536 - val_acc: 0.6667
Epoch 986/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.5164 - acc: 0.7238 - val_loss: 0.5534 - val_acc: 0.6667
Epoch 987/1000
1/1 [==============================] - 0s 30ms/step - loss: 0.5162 - acc: 0.7238 - val_loss: 0.5532 - val_acc: 0.6667
Epoch 988/1000
1/1 [==============================] - 0s 30ms/step - loss: 0.5160 - acc: 0.7238 - val_loss: 0.5530 - val_acc: 0.6667
Epoch 989/1000
1/1 [==============================] - 0s 29ms/step - loss: 0.5158 - 

In [18]:
predicoes = modelo.predict(x_teste) #Aplicar previsões
print(predicoes)

2/2 [==============================] - 0s 3ms/step
[[1.48243112e-02 4.34997588e-01 5.50178170e-01]
 [1.70356631e-02 4.46421325e-01 5.36542952e-01]
 [2.21164300e-04 2.63216138e-01 7.36562610e-01]
 [3.49276396e-03 3.70541900e-01 6.25965238e-01]
 [2.00397857e-02 4.49016035e-01 5.30944169e-01]
 [1.11225042e-02 4.27666903e-01 5.61210632e-01]
 [3.21046822e-03 3.70196253e-01 6.26593292e-01]
 [1.49814016e-03 3.33614707e-01 6.64887130e-01]
 [7.22523451e-01 1.85462654e-01 9.20138508e-02]
 [7.22454429e-01 1.85521930e-01 9.20235738e-02]
 [2.89655058e-03 3.59308630e-01 6.37794852e-01]
 [4.16474976e-03 3.82265449e-01 6.13569736e-01]
 [6.96095169e-01 2.01858088e-01 1.02046736e-01]
 [2.80669350e-02 4.58707482e-01 5.13225675e-01]
 [4.15772060e-03 3.75983745e-01 6.19858503e-01]
 [2.57394626e-03 3.59795481e-01 6.37630463e-01]
 [6.99495757e-03 4.04061586e-01 5.88943481e-01]
 [3.80694401e-03 3.72053444e-01 6.24139667e-01]
 [2.61020870e-03 3.57336104e-01 6.40053689e-01]
 [1.31835509e-02 4.29877967e-01 5.569

In [27]:
import numpy as np
np.set_printoptions(formatter={'float': lambda x: "{0:0.2f}".format(x)})#Imprimir somente duas casas decimais.
print(predicoes)

[[0.01 0.56 0.42]
 [0.00 0.19 0.81]
 [0.96 0.04 0.00]
 [0.00 0.12 0.88]
 [0.02 0.52 0.47]
 [0.96 0.04 0.00]
 [0.00 0.24 0.76]
 [0.03 0.69 0.28]
 [0.03 0.66 0.31]
 [0.00 0.41 0.58]
 [0.02 0.63 0.35]
 [0.04 0.57 0.39]
 [0.94 0.06 0.00]
 [0.05 0.69 0.26]
 [0.01 0.54 0.45]
 [0.01 0.47 0.52]
 [0.00 0.20 0.80]
 [0.97 0.03 0.00]
 [0.97 0.03 0.00]
 [0.03 0.62 0.35]
 [0.01 0.51 0.48]
 [0.01 0.60 0.38]
 [0.00 0.27 0.73]
 [0.00 0.37 0.62]
 [0.01 0.45 0.55]
 [0.94 0.06 0.00]
 [0.00 0.17 0.83]
 [0.00 0.16 0.84]
 [0.00 0.12 0.88]
 [0.00 0.40 0.59]
 [0.03 0.68 0.28]
 [0.01 0.53 0.46]
 [0.94 0.06 0.00]
 [0.95 0.05 0.00]
 [0.00 0.33 0.67]
 [0.96 0.04 0.00]
 [0.90 0.10 0.00]
 [0.04 0.65 0.31]
 [0.96 0.04 0.00]
 [0.00 0.33 0.67]
 [0.95 0.05 0.00]
 [0.00 0.15 0.85]
 [0.96 0.04 0.00]
 [0.03 0.63 0.34]
 [0.01 0.51 0.48]]
