In [1]:
import warnings
warnings.filterwarnings('ignore')
from sklearn.datasets import load_iris
import pandas as pd
iris = load_iris()
x = pd.DataFrame(iris.data, columns=[iris.feature_names])
y = pd.Series(iris.target)

In [2]:
x.head()

sepal length (cm) sepal width (cm) petal length (cm) petal width (cm)
0               5.1              3.5               1.4              0.2
1               4.9              3.0               1.4              0.2
2               4.7              3.2               1.3              0.2
3               4.6              3.1               1.5              0.2
4               5.0              3.6               1.4              0.2

In [3]:
y.value_counts()

0    50
1    50
2    50
Name: count, dtype: int64

In [4]:
#!pip3 install tensorflow
#Instale o tensorflow e nada mais!!!

In [7]:
import tensorflow
import keras
from tensorflow.python.keras.utils import np_utils
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D,Dropout
from tensorflow.keras.layers import Dense, Activation, Flatten
from tensorflow.keras.utils import to_categorical
from tensorflow.keras import backend as K 
from sklearn.model_selection import train_test_split
from tensorflow.keras import callbacks
y_convertido = np_utils.to_categorical(y) #convertendo a coluna de valores em uma matriz de classes (one hot encoding)

In [8]:
y_convertido

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [9]:
from sklearn.model_selection import train_test_split
x_treino, x_teste, y_treino, y_teste = train_test_split(x, y_convertido, test_size = 0.3)# 30% para teste

In [10]:
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.optimizers import SGD

In [12]:
modelo = Sequential()
#Construimos a rede neural adicionando camadas por meio do comando ".add". O primeiro argumento consiste no nùmero de neurônios
#que aquela camada terá. Também podemos informar o modelo de inicialização das variáveis e a função de ativação nessa camada.
modelo.add(Dense(10, input_dim=4, kernel_initializer='normal', activation='relu')) #input_dim é a quantidade de neurônios de
#entrada, que nesse caso são 4 variáveis preditoras
modelo.add(Dense(3, kernel_initializer='normal', activation='softmax')) #Essa é a saida (3 neurônios pois são 3 classes)
#A função softmax para a saída costuma ser usada em problemas de classificação. Ela dá como resultado probabilidades de pertencer
#a cada uma das classes (softmax / sigmoid / relu)

In [13]:
otimizador = keras.optimizers.SGD()

In [14]:
x_treino.shape

(105, 4)

In [15]:
modelo.compile(loss='categorical_crossentropy', optimizer=otimizador, metrics=['acc']) #"acc" é a metrica de acurácia
modelo.fit(x_treino, y_treino, epochs=1000, batch_size=105, validation_data=(x_teste, y_teste), verbose=1)

Epoch 1/1000


1/1 [==============================] - 1s 628ms/step - loss: 1.1009 - acc: 0.3524 - val_loss: 1.1051 - val_acc: 0.2889
Epoch 2/1000
1/1 [==============================] - 0s 27ms/step - loss: 1.1002 - acc: 0.3524 - val_loss: 1.1042 - val_acc: 0.2889
Epoch 3/1000
1/1 [==============================] - 0s 33ms/step - loss: 1.0995 - acc: 0.3524 - val_loss: 1.1034 - val_acc: 0.2889
Epoch 4/1000
1/1 [==============================] - 0s 31ms/step - loss: 1.0988 - acc: 0.3524 - val_loss: 1.1026 - val_acc: 0.2889
Epoch 5/1000
1/1 [==============================] - 0s 33ms/step - loss: 1.0982 - acc: 0.3524 - val_loss: 1.1018 - val_acc: 0.2889
Epoch 6/1000
1/1 [==============================] - 0s 32ms/step - loss: 1.0975 - acc: 0.3905 - val_loss: 1.1009 - val_acc: 0.4444
Epoch 7/1000
1/1 [==============================] - 0s 31ms/step - loss: 1.0968 - acc: 0.4952 - val_loss: 1.1001 - val_acc: 0.5333
Epoch 8/1000
1/1 [==============================] - 0s 33ms/step - loss: 1.0962 

1/1 [==============================] - 0s 27ms/step - loss: 1.0682 - acc: 0.3429 - val_loss: 1.0640 - val_acc: 0.3111
Epoch 60/1000
1/1 [==============================] - 0s 31ms/step - loss: 1.0676 - acc: 0.3429 - val_loss: 1.0633 - val_acc: 0.3111
Epoch 61/1000
1/1 [==============================] - 0s 28ms/step - loss: 1.0670 - acc: 0.3429 - val_loss: 1.0626 - val_acc: 0.3111
Epoch 62/1000
1/1 [==============================] - 0s 27ms/step - loss: 1.0664 - acc: 0.3429 - val_loss: 1.0618 - val_acc: 0.3111
Epoch 63/1000
1/1 [==============================] - 0s 26ms/step - loss: 1.0658 - acc: 0.3429 - val_loss: 1.0611 - val_acc: 0.3111
Epoch 64/1000
1/1 [==============================] - 0s 27ms/step - loss: 1.0652 - acc: 0.3429 - val_loss: 1.0603 - val_acc: 0.3111
Epoch 65/1000
1/1 [==============================] - 0s 26ms/step - loss: 1.0646 - acc: 0.3429 - val_loss: 1.0596 - val_acc: 0.3111
Epoch 66/1000
1/1 [==============================] - 0s 27ms/step - loss: 1.0640 - acc: 0.

1/1 [==============================] - 0s 26ms/step - loss: 1.0186 - acc: 0.4762 - val_loss: 1.0055 - val_acc: 0.5333
Epoch 122/1000
1/1 [==============================] - 0s 27ms/step - loss: 1.0176 - acc: 0.4952 - val_loss: 1.0043 - val_acc: 0.5333
Epoch 123/1000
1/1 [==============================] - 0s 26ms/step - loss: 1.0165 - acc: 0.5048 - val_loss: 1.0032 - val_acc: 0.5333
Epoch 124/1000
1/1 [==============================] - 0s 27ms/step - loss: 1.0155 - acc: 0.5143 - val_loss: 1.0020 - val_acc: 0.5333
Epoch 125/1000
1/1 [==============================] - 0s 28ms/step - loss: 1.0144 - acc: 0.5333 - val_loss: 1.0008 - val_acc: 0.5333
Epoch 126/1000
1/1 [==============================] - 0s 26ms/step - loss: 1.0133 - acc: 0.5429 - val_loss: 0.9996 - val_acc: 0.5333
Epoch 127/1000
1/1 [==============================] - 0s 28ms/step - loss: 1.0122 - acc: 0.5524 - val_loss: 0.9984 - val_acc: 0.5333
Epoch 128/1000
1/1 [==============================] - 0s 27ms/step - loss: 1.0111 - 

Epoch 183/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.9370 - acc: 0.6571 - val_loss: 0.9184 - val_acc: 0.6889
Epoch 184/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.9354 - acc: 0.6571 - val_loss: 0.9168 - val_acc: 0.6889
Epoch 185/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.9338 - acc: 0.6571 - val_loss: 0.9152 - val_acc: 0.6889
Epoch 186/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.9322 - acc: 0.6571 - val_loss: 0.9135 - val_acc: 0.6889
Epoch 187/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.9306 - acc: 0.6571 - val_loss: 0.9119 - val_acc: 0.6889
Epoch 188/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.9291 - acc: 0.6571 - val_loss: 0.9103 - val_acc: 0.6889
Epoch 189/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.9275 - acc: 0.6571 - val_loss: 0.9087 - val_acc: 0.6889
Epoch 190/1000
1/1 [==============================] - 0s 28ms/step - 

1/1 [==============================] - 0s 26ms/step - loss: 0.8401 - acc: 0.6571 - val_loss: 0.8206 - val_acc: 0.6889
Epoch 245/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.8385 - acc: 0.6571 - val_loss: 0.8190 - val_acc: 0.6889
Epoch 246/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.8369 - acc: 0.6571 - val_loss: 0.8175 - val_acc: 0.6889
Epoch 247/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.8352 - acc: 0.6571 - val_loss: 0.8159 - val_acc: 0.6889
Epoch 248/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.8336 - acc: 0.6571 - val_loss: 0.8144 - val_acc: 0.6889
Epoch 249/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.8320 - acc: 0.6571 - val_loss: 0.8128 - val_acc: 0.6889
Epoch 250/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.8303 - acc: 0.6571 - val_loss: 0.8113 - val_acc: 0.6889
Epoch 251/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.8287 - 

Epoch 306/1000
1/1 [==============================] - 0s 34ms/step - loss: 0.7335 - acc: 0.6667 - val_loss: 0.7231 - val_acc: 0.6889
Epoch 307/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.7317 - acc: 0.6667 - val_loss: 0.7216 - val_acc: 0.6889
Epoch 308/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.7299 - acc: 0.6762 - val_loss: 0.7200 - val_acc: 0.6889
Epoch 309/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.7281 - acc: 0.6762 - val_loss: 0.7184 - val_acc: 0.6889
Epoch 310/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.7263 - acc: 0.6762 - val_loss: 0.7168 - val_acc: 0.6889
Epoch 311/1000
1/1 [==============================] - 0s 30ms/step - loss: 0.7245 - acc: 0.6762 - val_loss: 0.7152 - val_acc: 0.6889
Epoch 312/1000
1/1 [==============================] - 0s 29ms/step - loss: 0.7228 - acc: 0.6762 - val_loss: 0.7136 - val_acc: 0.6889
Epoch 313/1000
1/1 [==============================] - 0s 27ms/step - 

1/1 [==============================] - 0s 28ms/step - loss: 0.6301 - acc: 0.6952 - val_loss: 0.6313 - val_acc: 0.7778
Epoch 368/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.6286 - acc: 0.7048 - val_loss: 0.6299 - val_acc: 0.7778
Epoch 369/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.6271 - acc: 0.7048 - val_loss: 0.6285 - val_acc: 0.7778
Epoch 370/1000
1/1 [==============================] - 0s 30ms/step - loss: 0.6256 - acc: 0.7048 - val_loss: 0.6272 - val_acc: 0.7778
Epoch 371/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.6241 - acc: 0.7048 - val_loss: 0.6258 - val_acc: 0.7778
Epoch 372/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.6226 - acc: 0.7048 - val_loss: 0.6245 - val_acc: 0.7778
Epoch 373/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.6211 - acc: 0.7048 - val_loss: 0.6231 - val_acc: 0.7778
Epoch 374/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.6197 - 

Epoch 429/1000
1/1 [==============================] - 0s 30ms/step - loss: 0.5506 - acc: 0.8286 - val_loss: 0.5582 - val_acc: 0.8444
Epoch 430/1000
1/1 [==============================] - 0s 31ms/step - loss: 0.5495 - acc: 0.8381 - val_loss: 0.5572 - val_acc: 0.8444
Epoch 431/1000
1/1 [==============================] - 0s 31ms/step - loss: 0.5485 - acc: 0.8476 - val_loss: 0.5562 - val_acc: 0.8444
Epoch 432/1000
1/1 [==============================] - 0s 31ms/step - loss: 0.5474 - acc: 0.8476 - val_loss: 0.5552 - val_acc: 0.8444
Epoch 433/1000
1/1 [==============================] - 0s 31ms/step - loss: 0.5464 - acc: 0.8476 - val_loss: 0.5543 - val_acc: 0.8444
Epoch 434/1000
1/1 [==============================] - 0s 33ms/step - loss: 0.5454 - acc: 0.8476 - val_loss: 0.5533 - val_acc: 0.8444
Epoch 435/1000
1/1 [==============================] - 0s 30ms/step - loss: 0.5444 - acc: 0.8476 - val_loss: 0.5523 - val_acc: 0.8444
Epoch 436/1000
1/1 [==============================] - 0s 34ms/step - 

1/1 [==============================] - 0s 31ms/step - loss: 0.4964 - acc: 0.9048 - val_loss: 0.5066 - val_acc: 0.8667
Epoch 491/1000
1/1 [==============================] - 0s 31ms/step - loss: 0.4956 - acc: 0.9048 - val_loss: 0.5058 - val_acc: 0.8667
Epoch 492/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.4949 - acc: 0.9048 - val_loss: 0.5051 - val_acc: 0.8667
Epoch 493/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.4941 - acc: 0.9048 - val_loss: 0.5044 - val_acc: 0.8667
Epoch 494/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.4934 - acc: 0.9048 - val_loss: 0.5037 - val_acc: 0.8667
Epoch 495/1000
1/1 [==============================] - 0s 31ms/step - loss: 0.4927 - acc: 0.9048 - val_loss: 0.5030 - val_acc: 0.8667
Epoch 496/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.4920 - acc: 0.9048 - val_loss: 0.5023 - val_acc: 0.8667
Epoch 497/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.4912 - 

Epoch 552/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.4562 - acc: 0.9333 - val_loss: 0.4666 - val_acc: 0.9333
Epoch 553/1000
1/1 [==============================] - 0s 30ms/step - loss: 0.4556 - acc: 0.9333 - val_loss: 0.4660 - val_acc: 0.9333
Epoch 554/1000
1/1 [==============================] - 0s 31ms/step - loss: 0.4550 - acc: 0.9333 - val_loss: 0.4654 - val_acc: 0.9333
Epoch 555/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.4545 - acc: 0.9333 - val_loss: 0.4648 - val_acc: 0.9333
Epoch 556/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.4539 - acc: 0.9333 - val_loss: 0.4643 - val_acc: 0.9333
Epoch 557/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.4534 - acc: 0.9429 - val_loss: 0.4637 - val_acc: 0.9333
Epoch 558/1000
1/1 [==============================] - 0s 30ms/step - loss: 0.4528 - acc: 0.9429 - val_loss: 0.4631 - val_acc: 0.9333
Epoch 559/1000
1/1 [==============================] - 0s 26ms/step - 

1/1 [==============================] - 0s 28ms/step - loss: 0.4247 - acc: 0.9619 - val_loss: 0.4340 - val_acc: 0.9556
Epoch 614/1000
1/1 [==============================] - 0s 29ms/step - loss: 0.4242 - acc: 0.9619 - val_loss: 0.4335 - val_acc: 0.9556
Epoch 615/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.4238 - acc: 0.9619 - val_loss: 0.4330 - val_acc: 0.9556
Epoch 616/1000
1/1 [==============================] - 0s 29ms/step - loss: 0.4233 - acc: 0.9619 - val_loss: 0.4325 - val_acc: 0.9556
Epoch 617/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.4228 - acc: 0.9619 - val_loss: 0.4320 - val_acc: 0.9556
Epoch 618/1000
1/1 [==============================] - 0s 30ms/step - loss: 0.4224 - acc: 0.9619 - val_loss: 0.4315 - val_acc: 0.9556
Epoch 619/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.4219 - acc: 0.9619 - val_loss: 0.4310 - val_acc: 0.9556
Epoch 620/1000
1/1 [==============================] - 0s 31ms/step - loss: 0.4214 - 

Epoch 675/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.3973 - acc: 0.9619 - val_loss: 0.4046 - val_acc: 0.9556
Epoch 676/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.3969 - acc: 0.9619 - val_loss: 0.4042 - val_acc: 0.9556
Epoch 677/1000
1/1 [==============================] - 0s 29ms/step - loss: 0.3964 - acc: 0.9619 - val_loss: 0.4037 - val_acc: 0.9556
Epoch 678/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.3960 - acc: 0.9619 - val_loss: 0.4033 - val_acc: 0.9556
Epoch 679/1000
1/1 [==============================] - 0s 30ms/step - loss: 0.3956 - acc: 0.9619 - val_loss: 0.4028 - val_acc: 0.9556
Epoch 680/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.3952 - acc: 0.9619 - val_loss: 0.4024 - val_acc: 0.9556
Epoch 681/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.3948 - acc: 0.9619 - val_loss: 0.4019 - val_acc: 0.9556
Epoch 682/1000
1/1 [==============================] - 0s 31ms/step - 

1/1 [==============================] - 0s 28ms/step - loss: 0.3729 - acc: 0.9714 - val_loss: 0.3780 - val_acc: 0.9778
Epoch 737/1000
1/1 [==============================] - 0s 29ms/step - loss: 0.3725 - acc: 0.9714 - val_loss: 0.3775 - val_acc: 0.9778
Epoch 738/1000
1/1 [==============================] - 0s 30ms/step - loss: 0.3721 - acc: 0.9714 - val_loss: 0.3771 - val_acc: 0.9778
Epoch 739/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.3718 - acc: 0.9714 - val_loss: 0.3767 - val_acc: 0.9778
Epoch 740/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.3714 - acc: 0.9714 - val_loss: 0.3763 - val_acc: 0.9778
Epoch 741/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.3710 - acc: 0.9714 - val_loss: 0.3759 - val_acc: 0.9778
Epoch 742/1000
1/1 [==============================] - 0s 29ms/step - loss: 0.3706 - acc: 0.9714 - val_loss: 0.3755 - val_acc: 0.9778
Epoch 743/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.3702 - 

Epoch 798/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.3499 - acc: 0.9714 - val_loss: 0.3526 - val_acc: 0.9778
Epoch 799/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.3496 - acc: 0.9714 - val_loss: 0.3522 - val_acc: 0.9778
Epoch 800/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.3492 - acc: 0.9714 - val_loss: 0.3518 - val_acc: 0.9778
Epoch 801/1000
1/1 [==============================] - 0s 30ms/step - loss: 0.3488 - acc: 0.9714 - val_loss: 0.3514 - val_acc: 0.9778
Epoch 802/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.3485 - acc: 0.9714 - val_loss: 0.3510 - val_acc: 0.9778
Epoch 803/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.3481 - acc: 0.9714 - val_loss: 0.3506 - val_acc: 0.9778
Epoch 804/1000
1/1 [==============================] - 0s 29ms/step - loss: 0.3478 - acc: 0.9714 - val_loss: 0.3502 - val_acc: 0.9778
Epoch 805/1000
1/1 [==============================] - 0s 31ms/step - 

1/1 [==============================] - 0s 27ms/step - loss: 0.3287 - acc: 0.9714 - val_loss: 0.3291 - val_acc: 0.9778
Epoch 860/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.3283 - acc: 0.9714 - val_loss: 0.3287 - val_acc: 0.9778
Epoch 861/1000
1/1 [==============================] - 0s 30ms/step - loss: 0.3280 - acc: 0.9714 - val_loss: 0.3283 - val_acc: 0.9778
Epoch 862/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.3277 - acc: 0.9714 - val_loss: 0.3280 - val_acc: 0.9778
Epoch 863/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.3273 - acc: 0.9714 - val_loss: 0.3276 - val_acc: 0.9778
Epoch 864/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.3270 - acc: 0.9714 - val_loss: 0.3272 - val_acc: 0.9778
Epoch 865/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.3267 - acc: 0.9714 - val_loss: 0.3268 - val_acc: 0.9778
Epoch 866/1000
1/1 [==============================] - 0s 33ms/step - loss: 0.3263 - 

Epoch 921/1000
1/1 [==============================] - 0s 29ms/step - loss: 0.3084 - acc: 0.9714 - val_loss: 0.3066 - val_acc: 0.9778
Epoch 922/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.3081 - acc: 0.9714 - val_loss: 0.3063 - val_acc: 0.9778
Epoch 923/1000
1/1 [==============================] - 0s 29ms/step - loss: 0.3077 - acc: 0.9714 - val_loss: 0.3059 - val_acc: 0.9778
Epoch 924/1000
1/1 [==============================] - 0s 45ms/step - loss: 0.3074 - acc: 0.9714 - val_loss: 0.3056 - val_acc: 0.9778
Epoch 925/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.3071 - acc: 0.9714 - val_loss: 0.3052 - val_acc: 0.9778
Epoch 926/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.3068 - acc: 0.9714 - val_loss: 0.3049 - val_acc: 0.9778
Epoch 927/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.3065 - acc: 0.9714 - val_loss: 0.3045 - val_acc: 0.9778
Epoch 928/1000
1/1 [==============================] - 0s 27ms/step - 

1/1 [==============================] - 0s 29ms/step - loss: 0.2897 - acc: 0.9714 - val_loss: 0.2860 - val_acc: 0.9778
Epoch 983/1000
1/1 [==============================] - 0s 29ms/step - loss: 0.2894 - acc: 0.9714 - val_loss: 0.2857 - val_acc: 0.9778
Epoch 984/1000
1/1 [==============================] - 0s 29ms/step - loss: 0.2891 - acc: 0.9714 - val_loss: 0.2853 - val_acc: 0.9778
Epoch 985/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.2888 - acc: 0.9714 - val_loss: 0.2850 - val_acc: 0.9778
Epoch 986/1000
1/1 [==============================] - 0s 27ms/step - loss: 0.2885 - acc: 0.9714 - val_loss: 0.2847 - val_acc: 0.9778
Epoch 987/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.2882 - acc: 0.9714 - val_loss: 0.2844 - val_acc: 0.9778
Epoch 988/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.2879 - acc: 0.9714 - val_loss: 0.2840 - val_acc: 0.9778
Epoch 989/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.2876 - 

In [16]:
predicoes = modelo.predict(x_teste)
print(predicoes)

2/2 [==============================] - 0s 2ms/step
[[9.71964061e-01 2.79393420e-02 9.65427025e-05]
 [1.15527480e-03 3.94960254e-01 6.03884459e-01]
 [7.56360358e-04 2.58867711e-01 7.40375936e-01]
 [2.88580335e-03 4.38463092e-01 5.58651030e-01]
 [9.62937832e-01 3.68601121e-02 2.02006093e-04]
 [9.66426730e-01 3.34179401e-02 1.55304762e-04]
 [9.66004670e-01 3.38344574e-02 1.60840937e-04]
 [9.61416364e-01 3.83960679e-02 1.87514088e-04]
 [1.02578206e-05 7.51230270e-02 9.24866736e-01]
 [9.44696665e-01 5.49023449e-02 4.01048455e-04]
 [8.20885689e-05 1.35291800e-01 8.64626169e-01]
 [2.24388819e-02 7.08173633e-01 2.69387484e-01]
 [7.71511171e-04 2.90030420e-01 7.09197998e-01]
 [1.55199682e-02 6.84246600e-01 3.00233454e-01]
 [2.29315046e-04 2.15631321e-01 7.84139395e-01]
 [4.61999476e-02 7.21457481e-01 2.32342616e-01]
 [8.08976367e-02 7.00172782e-01 2.18929574e-01]
 [8.27445015e-02 7.46165037e-01 1.71090543e-01]
 [1.07990345e-02 5.94655156e-01 3.94545734e-01]
 [7.05314742e-05 1.62907958e-01 8.370

In [17]:
import numpy as np
np.set_printoptions(formatter={'float': lambda x: "{0:0.2f}".format(x)})
print(predicoes)

[[0.97 0.03 0.00]
 [0.00 0.39 0.60]
 [0.00 0.26 0.74]
 [0.00 0.44 0.56]
 [0.96 0.04 0.00]
 [0.97 0.03 0.00]
 [0.97 0.03 0.00]
 [0.96 0.04 0.00]
 [0.00 0.08 0.92]
 [0.94 0.05 0.00]
 [0.00 0.14 0.86]
 [0.02 0.71 0.27]
 [0.00 0.29 0.71]
 [0.02 0.68 0.30]
 [0.00 0.22 0.78]
 [0.05 0.72 0.23]
 [0.08 0.70 0.22]
 [0.08 0.75 0.17]
 [0.01 0.59 0.39]
 [0.00 0.16 0.84]
 [0.03 0.69 0.27]
 [0.00 0.19 0.81]
 [0.00 0.20 0.80]
 [0.00 0.30 0.69]
 [0.03 0.67 0.30]
 [0.04 0.74 0.22]
 [0.95 0.05 0.00]
 [0.00 0.43 0.56]
 [0.00 0.34 0.66]
 [0.94 0.06 0.00]
 [0.94 0.06 0.00]
 [0.92 0.08 0.00]
 [0.94 0.06 0.00]
 [0.00 0.28 0.72]
 [0.01 0.57 0.42]
 [0.00 0.29 0.71]
 [0.00 0.24 0.76]
 [0.00 0.24 0.76]
 [0.00 0.54 0.46]
 [0.00 0.22 0.78]
 [0.00 0.34 0.66]
 [0.96 0.04 0.00]
 [0.02 0.57 0.41]
 [0.97 0.03 0.00]
 [0.01 0.54 0.45]]
